### ISSUE TITLE
Cesta k souborům

### ISSUE THREAD

**Issue by jakubkratina** [shoptet/shoptet-bender#14]
Zdravím Pavle,

dle dokumentace je potřeba vytvořit `src` adresář a v něm `script.js` a `styles.css` soubory (viz `Inside your project folder create another folder named "src"`)

Nicméně dle webpack configu je potřeba mít v src ještě jeden z následujících adresářů:
```
const folders = ['footer', 'header', 'index'];
```

Je možné, že dokumentace není aktualizovaná nebo dělám něco špatně?

Díky moc.

Jakub

**Comment by JanMolcik** [comment]
Měl jsem stejný problém, vyřešil jsem přidáním podadresáře `/src/header/...` a v něm až soubory `script.js` a `styles.css`. Až potom webpack zaregistroval změny souborů a zbuildí do `/dist` jako `scripts.header.js` a `styles.header.css`.

**Comment by pavelhusa** [comment]
Dobrý den, 
omlouvám se, že jste čekali na odpověď tak dlouho. Přidám GHA, abych byl rovnou přidaný jako assignee k novým issue.
Readme jsem upravil v commitu https://github.com/shoptet/shoptet-bender/commit/52f786ae961424534562b7f21c2d251761176a98. Takže zavírám issue. Děkuji a přeji hezký víkend.
Pavel
