### ISSUE TITLE
Add to description part "Usage", name of the folder to watch

### ISSUE THREAD

**Issue by ivancik-jakub** [shoptet/shoptet-bender#8]
I am a beginner in CLI so if were somebody similar to me I would like to be guided how to set "source" folder of .css and .js files. So it could be something like:

**Step-by-step guide to start**
1. Create a folder for your files (css, js) that need to be injected to remote e-shop on localhost (let's say "my-project")
2. Inside your project folder create another folder named "src"
3. Create or move your "style.css" and "script.js" files into "src" folder
4. Run --remote e-shop in console (let's say "shp-bender --remote https://classic.shoptet.cz/")
5. And you're ready to go -> enjoy coding and development ;)

**Comment by pavelhusa** [comment]
Hi Jakub, will you propose the pull request, or should I do it? It is surely a great idea.

**Comment by ivancik-jakub** [comment]
Hi Pavel, I made a pull request. I wish you peaceful day.

**Comment by pavelhusa** [comment]
Hi Jakub, PR is merged. Thank you, and have a lovely weekend. closed by PR #9
